### ISSUE TITLE
Licensing of this code?

### ISSUE THREAD

**Issue by efung** [soulwire/FontMetrics#1]
Can you please include a `LICENSE` file in this repo? c.f. https://help.github.com/articles/licensing-a-repository/

**Comment by julientaq** [comment]
Hey! we want to use it for printed stuff, and we would be happy to know how you licence it. Thanks!

**Comment by soulwire** [comment]
Thanks for the prompt @efung and @julientaq - I've added an MIT license to the repo now.

**Comment by julientaq** [comment]
Thanks a lot for that choice too :D !
